name: Build

on:
  workflow_call:
  pull_request:
    paths: ['apps/**', 'packages/**', '.github/workflows/**']
  push:
    branches: [main]
    paths: ['apps/**', 'packages/**', '.github/workflows/**']

permissions:
  contents: read

jobs:
  api-build:
    name: API Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared-types
        run: pnpm --filter @ultiverse/shared-types build

      - name: Build API
        run: pnpm -C apps/api build

      - name: Upload API build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: apps/api/dist
          if-no-files-found: ignore

  web-build:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared-types
        run: pnpm --filter @ultiverse/shared-types build

      - name: Build Web
        run: pnpm -C apps/web build

      - name: Upload Web build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/web/dist
          if-no-files-found: ignore